### PR TITLE
montana: include XT1790 in list of device without NFC and with an e-c…

### PR DESCRIPTION
**Pull request by CypherNoodle**
…ompass

### CODE REVIEW

**Comment by JarlPenguin** [comment]
Already in treble branch?

**Comment by JarlPenguin** [comment]
Will pick later

**Comment by CypherNoodle** [comment]
Treble already have this change and cof branch not yet.

**Comment by JarlPenguin** [comment]
Solved here: 439e9c8cd99c6bf2ac633dbdd1c6c14997a0a9a6

**Pull request closed without merging**
