### PR TITLE
Add device name for PixelExperience

### PR DESCRIPTION
**Pull request by zjunior06**

### CODE REVIEW

**Review by JarlPenguin — COMMENTED** [review]
is there not supposed to be a quote after G5S?

**Comment by JarlPenguin** [comment]
ah ok lel

**Review by JarlPenguin — APPROVED** [review]
will squash merge if u don't mind

**Comment by zjunior06** [comment]
> will squash merge if u don't mind

better

**Comment by JarlPenguin** [comment]
`"Moto G5S \(sku.c_str()\)"` would this work? or "Moto G5S \(sku.c_str()\)"
i am nub ;_;

**Comment by zjunior06** [comment]
> `"Moto G5S \(sku.c_str()\)"` would this work? or `"Moto G5S \(\sku.c_str()\)\"`
> i am nub ;_;

never tested.

**Comment by JarlPenguin** [comment]
I've implemented it here in a different way: 920df3e0005fb6788bd3edd3d6a8c2903ef64e74

**Pull request closed without merging**
